
export const SET_CLOTH = "SET_CLOTH";
export const SET_CELEMENT = "SET_CELEMENT";
export const SET_TITLE_CLOTHES_TYPE = "SET_TITLE_CLOTHES_TYPE";
export const SET_CURRENT_GROUP_CLOTH = "SET_CURRENT_GROUP_CLOTH";
export const SET_FEW_CELEMENTS = "SET_FEW_CELEMENTS";
export const SET_CURRENT_CELEMENTS = "SET_CURRENT_CELEMENTS";
export const SET_TABLE_CLOTHES = "SET_TABLE_CLOTHES";
export const SET_INIT_DATA = "SET_INIT_DATA";